#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
  path: /accueil
  controller: App\Controller\DefaultController::accueil

faq:
  path: /faq
  controller: App\Controller\DefaultController::faq

design:
  path: /design
  controller: App\Controller\DefaultController::design

creer_article:
  path: /creer/{titre}/{contenu}
  controller: App\Controller\DefaultController::creer_article

article:
  path: /article/{id}
  controller: App\Controller\DefaultController::article

  ## findAll()
articles:
  path: /articles
  controller: App\Controller\DefaultController::articles

  ## findBy, findOneBy
articles_by:
  path: /articles/{prop}/{recherche}
  controller: App\Controller\DefaultController::articles_by

update:
  path: /update/{id}/{prop}/{valeur}
  controller: App\Controller\DefaultController::update

supprimer:
  path: /supprimer/{id}
  controller: App\Controller\DefaultController::supprimer

index:
  path: /creer_produit
  controller: App\Controller\ProduitController::index

produits_filtre:
  path: /produits/{prix}
  controller: App\Controller\ProduitController::produitsFiltre

produits_cat:
  path: /produits/categorie/{id}
  controller: App\Controller\ProduitController::produitsCat

creer_produit:
  path: /produit/creer
  controller: App\Controller\ProduitController::creerProduit