#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
  path: /accueil
  controller: App\Controller\DefaultController::accueil

faq:
  path: /faq
  controller: App\Controller\DefaultController::faq

design:
  path: design
  controller: App\Controller\DefaultController::design